import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PrivateKey } from '@bsv/sdk/primitives';
import Transaction from '@bsv/sdk/transaction/Transaction';
import { Protocol, Version, buildArbitratedPoolFundingTx, buildArbitratedPoolLock, buildArbitratedPoolOpeningState, buildArbitratedPoolState, mergeArbitratedPoolBuyerArbiterSignatures, mergeArbitratedPoolBuyerSellerSignatures, mergeArbitratedPoolSellerArbiterSignatures, signArbitratedPoolAsArbiter, signArbitratedPoolAsBuyer, signArbitratedPoolAsSeller, validatePoolProtocol, verifyArbitratedPoolBuyerSignature } from '../../src/arbitrated_pool';

const fixture: Record<string, any> = JSON.parse(readFileSync(resolve(__dirname, '../../testdata/arbitrated_pool_v4_fixture.json'), 'utf8'));

test('v4 fixture rebuilds every funding, state, txid, signature and merge byte', async () => {
  validatePoolProtocol({ protocol: fixture.protocol, version: fixture.version });
  expect(fixture.protocol).toBe(Protocol);
  expect(fixture.version).toBe(Version);
  const buyer = PrivateKey.fromHex(fixture.buyerPrivHex);
  const seller = PrivateKey.fromHex(fixture.sellerPrivHex);
  const arbiter = PrivateKey.fromHex(fixture.arbiterPrivHex);
  const roles = { buyer: buyer.toPublicKey(), seller: seller.toPublicKey(), arbiter: arbiter.toPublicKey() };
  const funding = await buildArbitratedPoolFundingTx(fixture.buyerUtxos, fixture.poolAmount, buyer, roles, fixture.feeRate);
  const opening = await buildArbitratedPoolOpeningState(funding.tx, funding.poolAmount, roles, fixture.lockTime, fixture.feeRate);
  const build = (previousState: typeof opening, sequence: number, sellerAmount: number, arbiterAmount: number, paymentProof?: number[]) => buildArbitratedPoolState({ protocol: fixture.protocol, version: fixture.version, previousState, sequence, sellerAmount, arbiterAmount, poolAmount: funding.poolAmount, roles, feeRate: fixture.feeRate, paymentProof });
  const negotiation = await build(opening, fixture.negotiationSequence, fixture.negotiationSellerAmount, fixture.negotiationArbiterAmount);
  const paidArbiter = await build(negotiation, fixture.paidArbiterSequence, fixture.paidArbiterSellerAmount, fixture.paidArbiterAmount);
  const proofState = await build(paidArbiter, fixture.proofSequence, fixture.proofSellerAmount, fixture.proofArbiterAmount, Array.from(Buffer.from(fixture.paymentProofHex, 'hex')));
  expect(buildArbitratedPoolLock(roles).toHex()).toBe(fixture.lockHex);
  expect(funding.tx.toHex()).toBe(fixture.fundingHex);
  expect(funding.tx.id('hex')).toBe(fixture.fundingTxId);
  expect(funding.fee).toBe(fixture.fundingFee);
  expect(opening.toHex()).toBe(fixture.openingStateHex);
  expect(opening.id('hex')).toBe(fixture.openingStateTxId);
  expect(negotiation.toHex()).toBe(fixture.negotiationStateHex);
  expect(negotiation.id('hex')).toBe(fixture.negotiationStateTxId);
  expect(paidArbiter.toHex()).toBe(fixture.paidArbiterStateHex);
  expect(paidArbiter.id('hex')).toBe(fixture.paidArbiterStateTxId);
  expect(proofState.toHex()).toBe(fixture.proofStateHex);
  expect(proofState.id('hex')).toBe(fixture.proofStateTxId);
  expect(opening.outputs.map((output) => output.satoshis)).toEqual(fixture.openingOutputs);
  expect(negotiation.outputs.map((output) => output.satoshis)).toEqual(fixture.negotiationOutputs);
  expect(paidArbiter.outputs.map((output) => output.satoshis)).toEqual(fixture.paidArbiterOutputs);
  expect(proofState.outputs.map((output) => output.satoshis)).toEqual(fixture.proofOutputs);
  expect(proofState.outputs).toHaveLength(4);
  expect(proofState.outputs[3]?.lockingScript.toHex()).toBe('006a03010203');
  const buyerSignature = signArbitratedPoolAsBuyer(paidArbiter, funding.poolAmount, roles, buyer);
  const sellerSignature = signArbitratedPoolAsSeller(paidArbiter, funding.poolAmount, roles, seller);
  const arbiterSignature = signArbitratedPoolAsArbiter(paidArbiter, funding.poolAmount, roles, arbiter);
  expect(Buffer.from(buyerSignature).toString('hex')).toBe(fixture.buyerSignatureHex);
  expect(Buffer.from(sellerSignature).toString('hex')).toBe(fixture.sellerSignatureHex);
  expect(Buffer.from(arbiterSignature).toString('hex')).toBe(fixture.arbiterSignatureHex);
  expect(mergeArbitratedPoolBuyerSellerSignatures(paidArbiter, fixture.poolAmount, roles, buyerSignature, sellerSignature).toHex()).toBe(fixture.finalBuyerSellerHex);
  expect(mergeArbitratedPoolBuyerArbiterSignatures(paidArbiter, fixture.poolAmount, roles, buyerSignature, arbiterSignature).toHex()).toBe(fixture.finalBuyerArbiterHex);
  expect(mergeArbitratedPoolSellerArbiterSignatures(paidArbiter, fixture.poolAmount, roles, sellerSignature, arbiterSignature).toHex()).toBe(fixture.finalSellerArbiterHex);
});

test('v4 preserves and replaces payment proof only at output[3]', async () => {
  const buyer = PrivateKey.fromHex(fixture.buyerPrivHex);
  const seller = PrivateKey.fromHex(fixture.sellerPrivHex);
  const arbiter = PrivateKey.fromHex(fixture.arbiterPrivHex);
  const roles = { buyer: buyer.toPublicKey(), seller: seller.toPublicKey(), arbiter: arbiter.toPublicKey() };
  const funding = await buildArbitratedPoolFundingTx(fixture.buyerUtxos, fixture.poolAmount, buyer, roles, fixture.feeRate);
  const opening = await buildArbitratedPoolOpeningState(funding.tx, funding.poolAmount, roles, fixture.lockTime, fixture.feeRate);
  const paid = await buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: opening, sequence: 3, sellerAmount: 200, arbiterAmount: 100, poolAmount: fixture.poolAmount, roles, feeRate: 1 });
  const withProof = await buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: paid, sequence: 4, sellerAmount: 300, arbiterAmount: 200, poolAmount: fixture.poolAmount, roles, feeRate: 1, paymentProof: [1, 2, 3] });
  const preserved = await buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: withProof, sequence: 5, sellerAmount: 300, arbiterAmount: 200, poolAmount: fixture.poolAmount, roles, feeRate: 1 });
  const replaced = await buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: withProof, sequence: 5, sellerAmount: 300, arbiterAmount: 200, poolAmount: fixture.poolAmount, roles, feeRate: 1, paymentProof: [4, 5, 6] });
  expect(preserved.outputs[3].lockingScript.toHex()).toBe(withProof.outputs[3].lockingScript.toHex());
  expect(replaced.outputs[3].lockingScript.toHex()).not.toBe(withProof.outputs[3].lockingScript.toHex());
});

test('v4 rejects malformed state boundaries, overflow and stale signatures', async () => {
  const buyer = PrivateKey.fromHex(fixture.buyerPrivHex);
  const seller = PrivateKey.fromHex(fixture.sellerPrivHex);
  const arbiter = PrivateKey.fromHex(fixture.arbiterPrivHex);
  const roles = { buyer: buyer.toPublicKey(), seller: seller.toPublicKey(), arbiter: arbiter.toPublicKey() };
  const funding = await buildArbitratedPoolFundingTx(fixture.buyerUtxos, fixture.poolAmount, buyer, roles, fixture.feeRate);
  const state = await buildArbitratedPoolOpeningState(funding.tx, funding.poolAmount, roles, fixture.lockTime, fixture.feeRate);
  const signature = signArbitratedPoolAsBuyer(state, funding.poolAmount, roles, buyer);
  const invalid = Transaction.fromHex(state.toHex());
  invalid.outputs = state.outputs.slice(0, 2);
  await expect(buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: invalid, sequence: 3, sellerAmount: 1, arbiterAmount: 0, poolAmount: fixture.poolAmount, roles, feeRate: 1 })).rejects.toThrow('outputs');
  const tooMany = Transaction.fromHex(state.toHex());
  tooMany.outputs.push({ ...tooMany.outputs[0] });
  tooMany.outputs.push({ ...tooMany.outputs[0] });
  expect(() => verifyArbitratedPoolBuyerSignature(tooMany, fixture.poolAmount, roles, signature)).toThrow('outputs');
  const malformed = Transaction.fromHex(state.toHex());
  malformed.inputs.push({ ...malformed.inputs[0] });
  expect(() => signArbitratedPoolAsBuyer(malformed, fixture.poolAmount, roles, buyer)).toThrow('state');
  await expect(buildArbitratedPoolState({ protocol: Protocol, version: Version, previousState: state, sequence: 3, sellerAmount: 1, arbiterAmount: Number.MAX_SAFE_INTEGER, poolAmount: fixture.poolAmount, roles, feeRate: 1 })).rejects.toThrow('allocated');
  const changed = Transaction.fromHex(state.toHex());
  changed.inputs[0]!.sourceTransaction = state.inputs[0]!.sourceTransaction;
  const changedOutput = changed.outputs[1];
  if (!changedOutput || changedOutput.satoshis === undefined) throw new Error('changed output is missing');
  changedOutput.satoshis += 1;
  expect(() => verifyArbitratedPoolBuyerSignature(changed, fixture.poolAmount, roles, signature)).toThrow('verification');
});
